version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: hostel_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=hostel_user
      - POSTGRES_PASSWORD=hostel_pass
      - POSTGRES_DB=hostel_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:

